language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test -- --coverage
  - yarn run build
after_script:
  - COVERALLS_REPO_TOKEN=7FS4v5Dsec3186HyhtKiiWlpyT5VyOLqL yarn run coveralls
deploy:
  provider: pages
  skip_clanup: true
  github_token: $github_token
  local_dir: 
  on:
    branch: master